In [1]:
import quandl
import numpy as np 
from sklearn.linear_model import LinearRegression
from sklearn.svm import SVR
from sklearn.model_selection import train_test_split



In [15]:
#https://medium.com/@randerson112358/predict-stock-prices-using-python-machine-learning-53aa024da20a
# Get the stock data
df = quandl.get("WIKI/GOOGL")
# Take a look at the data
df.head()

Open    High     Low    Close      Volume  Ex-Dividend  \
Date                                                                   
2004-08-19  100.01  104.06   95.96  100.335  44659000.0          0.0   
2004-08-20  101.01  109.08  100.50  108.310  22834300.0          0.0   
2004-08-23  110.76  113.48  109.05  109.400  18256100.0          0.0   
2004-08-24  111.24  111.60  103.57  104.870  15247300.0          0.0   
2004-08-25  104.76  108.00  103.88  106.000   9188600.0          0.0   

            Split Ratio  Adj. Open  Adj. High   Adj. Low  Adj. Close  \
Date                                                                   
2004-08-19          1.0  50.159839  52.191109  48.128568   50.322842   
2004-08-20          1.0  50.661387  54.708881  50.405597   54.322689   
2004-08-23          1.0  55.551482  56.915693  54.693835   54.869377   
2004-08-24          1.0  55.792225  55.972783  51.945350   52.597363   
2004-08-25          1.0  52.542193  54.167209  52.100830   53.164113   

            Adj. Volume  
Date                     
2004-08-19   44659000.0  
2004-08-20   22834300.0  
2004-08-23   18256100.0  
2004-08-24   15247300.0  
2004-08-25    9188600.0

In [28]:
# Get the Adjusted Close Price 
df = df[['Adj. Close']] 
# Take a look at the new data 
df.head()

Adj. Close
Date                  
2004-08-19   50.322842
2004-08-20   54.322689
2004-08-23   54.869377
2004-08-24   52.597363
2004-08-25   53.164113

In [55]:
# A variable for predicting 'n' days out into the future
forecast_out = 3 #'n=30' days
#Create another column (the target ) shifted 'n' units up
df['Prediction'] = df[['Adj. Close']].shift(-forecast_out)
#print the new data set
df.tail(35)

Adj. Close  Prediction
Date                              
2018-02-06     1084.43     1043.43
2018-02-07     1055.41     1054.56
2018-02-08     1005.60     1054.14
2018-02-09     1043.43     1072.70
2018-02-12     1054.56     1091.36
2018-02-13     1054.14     1095.50
2018-02-14     1072.70     1103.59
2018-02-15     1091.36     1113.75
2018-02-16     1095.50     1109.90
2018-02-20     1103.59     1128.09
2018-02-21     1113.75     1143.70
2018-02-22     1109.90     1117.51
2018-02-23     1128.09     1103.92
2018-02-26     1143.70     1071.41
2018-02-27     1117.51     1084.14
2018-02-28     1103.92     1094.76
2018-03-01     1071.41     1100.90
2018-03-02     1084.14     1115.04
2018-03-05     1094.76     1129.38
2018-03-06     1100.90     1160.84
2018-03-07     1115.04     1165.93
2018-03-08     1129.38     1139.91
2018-03-09     1160.84     1148.89
2018-03-12     1165.93     1150.61
2018-03-13     1139.91     1134.42
2018-03-14     1148.89     1100.07
2018-03-15     1150.61     1095.80
2018-03-16     1134.42     1094.00
2018-03-19     1100.07     1053.15
2018-03-20     1095.80     1026.55
2018-03-21     1094.00     1054.09
2018-03-22     1053.15     1006.94
2018-03-23     1026.55         NaN
2018-03-26     1054.09         NaN
2018-03-27     1006.94         NaN

In [56]:
### Create the independent data set (X)  #######
# Convert the dataframe to a numpy array
X = np.array(df.drop(['Prediction'],1))

#Remove the last 'n' rows
X = X[:-forecast_out]
print(X)

[[  50.32284179]
 [  54.32268894]
 [  54.86937651]
 ...
 [1095.8       ]
 [1094.        ]
 [1053.15      ]]


In [57]:
### Create the dependent data set (y)  #####
# Convert the dataframe to a numpy array 
y = np.array(df['Prediction'])
# Get all of the y values except the last 'n' rows
y = y[:-forecast_out]
print(y)

[  52.59736302   53.16411252   54.12206964 ... 1026.55       1054.09
 1006.94      ]


In [43]:
# Split the data into 80% training and 20% testing
x_train, x_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [58]:
# Create and train the Support Vector Machine (Regressor) 
svr_rbf = SVR(kernel='rbf', C=1e3, gamma=0.1) 
svr_rbf.fit(x_train, y_train)

SVR(C=1000.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1, gamma=0.1,
  kernel='rbf', max_iter=-1, shrinking=True, tol=0.001, verbose=False)

In [59]:
# Testing Model: Score returns the coefficient of determination R^2 of the prediction. 
# The best possible score is 1.0
svm_confidence = svr_rbf.score(x_test, y_test)
print("svm confidence: ", svm_confidence)

svm confidence:  0.9700121000377637


In [60]:
# Create and train the Linear Regression  Model
lr = LinearRegression()
# Train the model
lr.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [62]:
# Testing Model: Score returns the coefficient of determination R^2 of the prediction. 
# The best possible score is 1.0
lr_confidence = lr.score(x_test, y_test)
print("lr confidence: ", lr_confidence)

lr confidence:  0.9766430069481921


In [63]:
# Set x_forecast equal to the last 30 rows of the original data set from Adj. Close column
x_forecast = np.array(df.drop(['Prediction'],1))[-forecast_out:]
print(x_forecast)

[[1026.55]
 [1054.09]
 [1006.94]]


In [64]:
# Print linear regression model predictions for the next '30' days
lr_prediction = lr.predict(x_forecast)
print(lr_prediction)

[1045.42577664 1073.41039337 1025.49918499]


In [65]:
# Print support vector regressor model predictions for the next '30' days
svm_prediction = svr_rbf.predict(x_forecast)
print(svm_prediction)

[1024.74584105 1016.90558299 1085.50166663]
